export type Room = {
  id: string;
  name: string;
  desc: string[];
  exits: Record<string, string>;
  items?: string[];
  loot?: string;
};

export const PLAYER = {
  name: "MIKE DEMOPOULOS",
  title: "Partnerships Lead // Technology Leader",
  location: "Hudson, Wisconsin, USA",
  email: "hey.demo@mikedemo.email",
  phone: "612.807.3601",
  linkedin: "in/mikedemopoulos",
  site: "mikedemo.com",
};

export const ROOMS: Record<string, Room> = {
  lobby: {
    id: "lobby",
    name: "THE ATRIUM",
    desc: [
      "A dim lobby lit by a single amber CRT. A brass plaque reads:",
      '  "MIKE DEMOPOULOS — 10+ years in business development, strategic',
      '   partnerships, and cross-functional leadership across the Americas,',
      '   EMEA, and APAC."',
      "Corridors lead in every direction. A humming server rack sits north.",
    ],
    exits: {
      north: "cloud",
      east: "guild",
      south: "forge",
      west: "academy",
      up: "council",
    },
    items: ["plaque", "crt"],
    loot: "BUSINESS CARD",
  },
  cloud: {
    id: "cloud",
    name: "THE CLOUD DECK — hosting.com",
    desc: [
      "Apr 2025 - Present · Ann Arbor, MI · PARTNERSHIPS LEAD, NORTH AMERICA",
      "High-performance clouds hum overhead, carrying business-critical apps.",
      "> Drove growth for U.S. digital agencies with tailored hosting solutions",
      "  and strategic account management.",
      "> Built strategic partnerships with key clients and industry partners,",
      "  lifting revenue growth and customer retention.",
      "> Generated new business across 100+ digital agencies via consultative",
      "  selling and relationship-driven outreach.",
    ],
    exits: { south: "lobby", east: "guild" },
    items: ["rack"],
    loot: "AGENCY LEDGER",
  },
  guild: {
    id: "guild",
    name: "THE PARTNER GUILD — Codeable",
    desc: [
      "Jun 2021 - Dec 2024 · Remote · HEAD OF PARTNERSHIPS",
      "A vast hall of a thousand affiliate banners, each stitched with a logo.",
      "> Led partnership development that significantly increased revenue,",
      "  activating new partners across multiple sectors.",
      "> Re-engaged the partner base and scaled conference activity to",
      "  unprecedented levels with Developer & Partner Communities.",
      "> Shipped integrations with Plesk and cPanel — reaching thousands of hosts.",
      "> Ran a 1,000+ partner in-house affiliate program and launched on the",
      "  TUNE affiliate network.",
    ],
    exits: { west: "lobby", north: "cloud", south: "treasury" },
    items: ["banners"],
    loot: "TUNE KEY",
  },
  treasury: {
    id: "treasury",
    name: "THE TREASURY — Joomla",
    desc: [
      "Jan 2019 - Jan 2024 · Remote · TREASURER",
      "Ledgers stacked to the ceiling. The world's 2nd-largest open source CMS.",
      "> Managed project budgets in QuickBooks and coordinated sponsorship teams",
      "  to keep the project financially stable.",
      "> Organized the international Joomla World Conference three years running.",
      "> Co-organized JoomlaDay Minnesota into North America's largest Joomla event.",
      "> Ran the marketing for the inaugural JoomlaDay MN — sold out.",
      "Still active since 2014: Event Organizer, Finance Team, World Conference Team.",
    ],
    exits: { north: "guild", west: "forge" },
    items: ["ledgers"],
    loot: "TREASURER SEAL",
  },
  forge: {
    id: "forge",
    name: "THE EVANGELIST'S FORGE — InMotion / BoldGrid",
    desc: [
      "Oct 2016 - Jun 2021 · Remote · BIZ DEV SPECIALIST / PRODUCT EVANGELIST",
      "A stage, a mic, and a wall of conference badges from a dozen countries.",
      "> Represented BoldGrid & InMotion Hosting at major industry events with",
      "  talks and influential guest content.",
      "> Drove biz-dev and M&A leads contributing to FOUR successful acquisitions.",
      "> Key in BoldGrid's rise from emerging brand to WordPress household name.",
      "> Led BoldGrid's integration with Plesk and cPanel.",
    ],
    exits: { north: "lobby", east: "treasury", west: "studio" },
    items: ["mic", "badges"],
    loot: "EVANGELIST MIC",
  },
  studio: {
    id: "studio",
    name: "THE STUDIO — MVP Marketing + Design / SPC",
    desc: [
      "Aug 2015 - Oct 2016 · Minneapolis, MN · SENIOR DIGITAL SERVICES MANAGER",
      "> 400%+ efficiency gain in the digital department within 12 months.",
      "> Partnered with AEs to win new clients and grow revenue.",
      "> Vendor evaluation & transition saving tens of thousands of dollars.",
      "",
      "Jun 2013 - Aug 2015 · Blaine, MN · LEAD DEVELOPER, SPC",
      "> Built and maintained 100+ websites for banking and insurance clients.",
      "> Upgraded 85 sites to Joomla 3 with zero data loss.",
    ],
    exits: { east: "forge", north: "academy" },
    items: ["terminal"],
    loot: "LEGACY CODEBASE",
  },
  academy: {
    id: "academy",
    name: "THE ACADEMY — Education & Certifications",
    desc: [
      "Chalk dust and neural nets.",
      "> MIT Professional Education, 2025 — AI and Machine Learning:",
      "  No Code AI and ML: Building Data Science Solutions.",
      "> Block, 2015 — UX Design.",
      "> The Art Institutes International–Minnesota, 2005 — Web Page,",
      "  Digital/Multimedia & Information Resources Design.",
      "> Minnesota Business Academy, 2004 — High School Diploma.",
      "CERTS: The Community MBA (CMX, 2021) · Disney's Approach to Business",
      "Excellence (Disney Institute, 2020) · Power MBA (2020).",
      "",
      "SKILLS unlocked: Strategic Partnerships · Channel Partners · M&A ·",
      "Developer Relations · B2B · Field Marketing · Public Speaking ·",
      "Leadership · WordPress · Joomla · PHP · SQL · CSS/HTML · HubSpot ·",
      "QuickBooks · Copilot · Machine Learning · Cloud Computing.",
    ],
    exits: { east: "lobby", south: "studio", up: "council" },
    items: ["diploma"],
    loot: "MIT CREDENTIAL",
  },
  council: {
    id: "council",
    name: "THE COUNCIL CHAMBER — Forbes Agency Council",
    desc: [
      "Jan 2026 - Present · MEMBER & GROUP LEADER",
      "A high round table above the clouds. Printing presses churn below.",
      "> Leads the Web Hosting & Infrastructure Group.",
      "> Contributes articles and quotes to Forbes.com on agency best practices.",
      "> Built and ran the group's content strategy and thought leadership.",
      "",
      "PUBLISHED (Forbes, 2026):",
      '  "The Lifespan Of SSL Certificates Is Shrinking, And Agencies Must Adapt"',
      '  "Green Website Hosting: What Agencies Should Know, And Where To Start"',
    ],
    exits: { down: "lobby" },
    items: ["press"],
    loot: "FORBES PEN",
  },
};

export const EXAMINE: Record<string, string> = {
  plaque: "Brass, well polished. 10+ years. Americas, EMEA, APAC. Still going.",
  crt: "An amber monitor showing a blinking cursor. It's waiting for you, too.",
  rack: "Blade servers for business-critical workloads. Uptime is a love language.",
  banners: "One thousand affiliate partners, plus a TUNE network banner, freshly hung.",
  ledgers: "QuickBooks exports for the world's second-largest open source CMS. Balanced.",
  mic: "Worn foam windscreen. It has told the BoldGrid story on many stages.",
  badges: "Conference lanyards from WordCamps, Joomla World Conferences, hosting summits.",
  terminal: "A green screen running Joomla 3. 85 sites migrated here without a scratch.",
  diploma: "MIT Professional Education, 2025. Signed, sealed, applied.",
  press: "A Forbes press proof, ink still wet on an SSL certificate op-ed.",
};

export const HELP = [
  "COMMANDS:",
  "  LOOK              re-read the current room",
  "  GO <dir>          n / s / e / w / up / down",
  "  <dir>             shortcut, e.g. NORTH or N",
  "  EXAMINE <thing>   inspect an object",
  "  TAKE <thing>      pick up the artifact here",
  "  INVENTORY / I     list artifacts collected",
  "  MAP               show known locations",
  "  CONTACT           reach the real human",
  "  RESUME            full career summary dump",
  "  CLEAR             wipe the screen",
  "  HELP              this list",
];
